### ISSUE TITLE
protected memory exception during Run call

### ISSUE THREAD

**Issue by andres-nemvalts** [joelself/FannCSharp#2]
Hello,
VS2015, x64, simple XOR test - all runs perfectly until Run call, which gives protected memory exception. Full solution included.
Why would that happen, if you could please investigate?
Thanks!
Andres

[EXCEPTION_MESSAGE.txt](https://github.com/joelself/FannCSharp/files/115487/EXCEPTION_MESSAGE.txt)
[DustBiterBabySteps.zip](https://github.com/joelself/FannCSharp/files/115488/DustBiterBabySteps.zip)

**Comment by joelself** [comment]
Thanks for the feedback! I was getting worried that nothing was working and people weren't bothering to report it. I'll take a look at this as soon as I can, probably tonight or tomorrow.

Edit: Extra thanks for providing so much info on the bug!

**Comment by andres-nemvalts** [comment]
Thank you, will be waiting!

**Comment by joelself** [comment]
The problem was I was manually maniputling an `IEnumerator`, which starts _before_ the first element in the collection. The recommended way of using `IEnumerator`s is with the `foreach' statement so I switched to that. After swiching to`foreach` for program ran fine. The check-in should have kicked off a build and when it is finished it should be accessible on the latest releases page (there should be a link to the releases page and a badge showing the latest release on this project's README.md.).

**Comment by andres-nemvalts** [comment]
It doesn't crash any more with the latest. Thank you!
